apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: monitoring
nodes:
- role: control-plane
  image: kindest/node:v1.23.0
- role: worker
  image: kindest/node:v1.23.0
- role: worker
  image: kindest/node:v1.23.0
- role: worker
  image: kindest/node:v1.23.0
