apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
  name: metrics
  namespace: metrics
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: metrics
  selector:
    app: metrics
status:
  loadBalancer: {}
