FROM python:3-slim AS build-env
ADD . /app
WORKDIR /app
RUN python3 -m venv . 
RUN /app/bin/pip install -r src/requirements.txt

FROM gcr.io/distroless/python3
COPY --from=build-env /app /app
ENV PYTHONPATH /app/lib/python3.10/site-packages/
WORKDIR /app/src
EXPOSE 5000
ENTRYPOINT [ "python3" ] 
CMD ["-m",  "flask", "run", "-h", "0.0.0", "-p", "5000" ]